window.LOGICNEST_CONFIG = {
  SUPABASE_URL: 'https://saymqnihmcrowapmrajj.supabase.co',
  SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNheW1xbmlobWNyb3dhcG1yYWpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc3MTI0MTcsImV4cCI6MjA5MzI4ODQxN30.2Fe_iQTczYVT5uRbk1RS4uJVgWi6aIeRXhXNDcPJJTg',
  ADMIN_PASSWORD: 'Sg6046770'
};
